# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Eagle Industrial Electric
email: info@eagleielectric.com
description: Eagle Industrial Electric, Inc. is an electrical contractor serving the City of Philadelphia and surrounding areas. Specializing in commercial building installations, high voltage cabling and substation construction, emergency generation installations, aviation projects, antenna & wireless systems installation, building systems installation, lighting retrofits, restaurant/retail fit outs, and complete electrical systems maintenance.  We offer 24-hour emergency service for any/all electrical situations that may arise.
baseurl: "file:///Users/droy/Documents/projects/eagle-industrial-electric/_site/" # the subpath of your site, e.g. /blog
url: "http://eagleielectric.com" # the base hostname & protocol for your site
github_username:  dave600

# Build settings
markdown: kramdown
theme: minima
